SEARCH_DIR("/usr/lib32/")
SEARCH_DIR("/lib32/")
SEARCH_DIR("/usr/lib/i386-linux-gnu/")
SEARCH_DIR("/lib/i386-linux-gnu/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/11/")
SEARCH_DIR("./")
SEARCH_DIR("/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/")
SEARCH_DIR("/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/opengl/lib/i386-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/config_lazarus/onlinepackagemanager/packages/BGRABitmap/bgrabitmap/lib/i386-linux-gtk2-3.3.1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/freetype/lib/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/packager/units/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/httpd22/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gdbint/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/sqlite/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/cdrom/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/zorba/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/chm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-xml/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/symbolic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libcurl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/ldap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/regexpr/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/tcl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/httpd24/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/oracle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libgd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pastojs/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-db/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libusb/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libvlc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libmagic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/openssl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/iconvenc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-fpcunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/bfd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-unicode/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libfontconfig/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/mysql/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-res/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/bzip2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libcups/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/modplug/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/ibase/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/a52/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-net/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/openal/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/opencl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fftw/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libpng/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/tplylib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/uuid/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/users/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fpindexer/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-pdf/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/numlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/imagemagick/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/odbc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/unixutil/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/lua/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/mad/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/hermes/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-web/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/jni/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-js/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/sdl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-generics/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libgc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-mustache/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/zlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/dts/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-async/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libpcre/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libenet/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pthreads/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-json/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-stl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libffi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libxml2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/oggvorbis/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fastcgi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/testinsight/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/graph/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gnome1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/ncurses/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fpgtk/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/webidl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/syslog/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/imlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libmicrohttpd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-registry/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libsee/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-console/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/opengles/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libnettle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/xforms/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gnutls/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/libtar/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/postgres/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/cairo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/utmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/dblib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fppkg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/dbus/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gitlab/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/newt/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/proj4/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-process/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/aspell/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pxlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fv/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/svgalib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/googleapi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fpmkunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/odata/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/ptc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/x11/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/vcl-compat/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/opengl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-css/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-report/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-passrc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/ggi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rsvg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/unzip/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pcap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-sdo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gdbm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gst/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-sound/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/bin/x86_64-linux/")
INPUT(
/usr/lib/i386-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/11/crtbegin.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/si_c21.o
/tmp/project1.o
/tmp/project1.or
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/system.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/fpintres.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/objpas.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/forms.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/extctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/interfaces.o
/tmp/hauptfenster.o
/tmp/anzeigeroptionen.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/classes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/sysutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/types.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/typinfo.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/math.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/custapp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/system.uitypes.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclstrconsts.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lcltype.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclproc.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclintf.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclversion.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclclasses.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/interfacebase.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lresources.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/graphics.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/menus.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lmessages.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/customtimer.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/actnlist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/clipbrd.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/helpintfs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/controls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/imglist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/themes.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazfileutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazutf8.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/maps.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/integerlist.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazmethodlist.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazloggerbase.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazutilities.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/graphtype.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/rtlconsts.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/sortbase.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/linux.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/baseunix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/unix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/errors.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/sysconst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/unixtype.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/unixutil.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/singleinstance.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsreferences.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/avl_tree.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazutf16.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/laztracer.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/graphmath.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazutilsstrconsts.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/cwstring.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/fpcadds.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/strutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/ctypes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/initc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/dynlibs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/unixcp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/dl.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/translations.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-json/jsonscanner.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-json/jsonparser.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-json/fpjson.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/fileutil.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lconvencoding.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/avglvltree.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/stringhashlist.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-json/jsonreader.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/variants.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/contnrs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/varutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/masks.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/dos.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/codepagescommon.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/codepagesasian.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/strings.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazclasses.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazdbglog.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/utf8process.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazsysutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpimage.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclplatformdef.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/intfgraphics.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazversion.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpreadbmp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpwritebmp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/bmpcomn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpreadpng.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpwritepng.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpreadtiff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpwritetiff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fptiffcmn.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/icnstypes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpimgcmn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/pngcomn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/zstream.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/zbase.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/gzio.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/hash/crc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/zdeflate.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/zinflate.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/trees.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/adler.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/infblock.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/infutil.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/infcodes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/inftrees.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/paszlib/inffast.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpcolorspace.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpcanvas.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpreadpnm.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpwritepnm.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpreadjpeg.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpwritejpeg.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpreadgif.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclrescache.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/clipping.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/jpegcomn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jpeglib.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdapimin.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdatasrc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdapistd.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jmorecfg.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdeferr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jinclude.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jerror.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jmemmgr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdmarker.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdinput.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcomapi.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jmemnobs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdmaster.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdcolor.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdsample.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdpostct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jddctmgr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdphuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdhuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdcoefct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdmainct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jquant1.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jquant2.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdmerge.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jidctfst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jidctint.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jidctflt.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jidctred.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcapistd.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcapimin.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jdatadst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcparam.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcinit.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcmarker.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcphuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jchuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcmaster.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jccolor.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcsample.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcprepct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcdctmgr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jccoefct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jcmainct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jfdctint.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jfdctfst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pasjpeg/jfdctflt.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazconfigstorage.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/dynqueue.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazstringutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/syncobjs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/system.timespan.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/pthreads/pthreads.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/tmschema.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/fgl.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-process/process.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-process/pipes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl/termio.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wslclclasses.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fpimgcanv.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/fppixlcanv.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/pixtools.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/ellipses.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-image/polygonfilltools.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsimglist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsproc.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsfactory.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/propertystorage.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/rttiutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsmenus.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/chm/fasthtmlparser.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wscontrols.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsforms.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/stdctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/popupnotifier.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/textstrings.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/extendedstrings.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsstdctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsextctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2disableliboverlay.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2int.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/x11/xlib.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/x11/x.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/gdk2x.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/gdk2pixbuf.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/gtk2.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/gdk2.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/glib2.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/pango.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/dialogs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/buttons.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/checklst.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/comctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2winapiwindow.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2globals.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2proc.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2def.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2fontcache.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2extra.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2msgqueue.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/dynhasharray.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/x11/xrender.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/cairo/cairo.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/atk.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/buttonpanel.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/dialogres.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/imagelistcache.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsbuttons.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/toolwin.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wscomctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wstoolwin.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsdialogs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/taskdlgemulation.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/rtl-objpas/dateutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wschecklst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/gtk2/gtk2ext.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-base/uriparser.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/extdlgs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclmessageglue.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2debug.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/calendar.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/calcform.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wscalendar.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsextdlgs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/lclmemmanager.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsprivate.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazlinkedlist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsfactory.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsstdctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wscontrols.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wschecklst.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2themes.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/spin.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/grids.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/pairsplitter.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsbuttons.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wscalendar.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wscomctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsdialogs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsextctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsextdlgs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsforms.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsgrids.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsimglist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsmenus.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wsspin.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2wspairsplitter.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/unitywsctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsspin.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/fcl-xml/htmldefs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/maskedit.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/dynamicarray.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/laz2_xmlcfg.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lcsvutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/lazfilecache.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/laz2_dom.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/laz2_xmlread.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/laz2_xmlwrite.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/i386-linux/laz2_xmlutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wsgrids.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/wspairsplitter.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2cellrenderer.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2listviewtreemodel.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglglad_gl.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglunit.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogltextur.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogltexturvao.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogltexturkoerper.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglvector.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglmatrix.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogllighting.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglsteuerung.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglbackground.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogldarstellung.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglvao.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlianzeigeschiene.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlifluegeli.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlistandrohr.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vliarmaflex.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlibasis.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlistutzen.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vliflansch.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlischwimmer.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vlidichtung.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Examples/10_-_VLI/VLI_Package/lib/i386-linux/vliwasser.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/opengl/lib/i386-linux/gtk2/openglcontext.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglcamera.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/opengl/lib/i386-linux/gtk2/glgtkglxcontext.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/x11/xutil.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/opengl/gl.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/opengl/glx.o
/home/tux/fpcupdeluxe_trunk/fpc/units/i386-linux/opengl/glext.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogldebug.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglshader.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/ogllightingshader.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglvbo.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglubo.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/i386-linux/oglvectors.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/lcl.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/alllclintfunits.o
/home/tux/fpcupdeluxe_trunk/lazarus/packager/units/i386-linux/lazaruspackageintf.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/i386-linux/gtk2/gtk2windows.o
)
INPUT(
-ldl
-lpthread
-lgdk-x11-2.0
-lgtk-x11-2.0
-lX11
-lgdk_pixbuf-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
-lGL
-lm
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/11/crtend.o
/usr/lib/i386-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  /DISCARD/ : {*(.debug_frame)}
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
