{$IFDEF read_interface}


function glmc_ease_linear(t: single): single; cdecl; external libcglm;
function glmc_ease_sine_in(t: single): single; cdecl; external libcglm;
function glmc_ease_sine_out(t: single): single; cdecl; external libcglm;
function glmc_ease_sine_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_quad_in(t: single): single; cdecl; external libcglm;
function glmc_ease_quad_out(t: single): single; cdecl; external libcglm;
function glmc_ease_quad_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_cubic_in(t: single): single; cdecl; external libcglm;
function glmc_ease_cubic_out(t: single): single; cdecl; external libcglm;
function glmc_ease_cubic_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_quart_in(t: single): single; cdecl; external libcglm;
function glmc_ease_quart_out(t: single): single; cdecl; external libcglm;
function glmc_ease_quart_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_quint_in(t: single): single; cdecl; external libcglm;
function glmc_ease_quint_out(t: single): single; cdecl; external libcglm;
function glmc_ease_quint_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_exp_in(t: single): single; cdecl; external libcglm;
function glmc_ease_exp_out(t: single): single; cdecl; external libcglm;
function glmc_ease_exp_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_circ_in(t: single): single; cdecl; external libcglm;
function glmc_ease_circ_out(t: single): single; cdecl; external libcglm;
function glmc_ease_circ_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_back_in(t: single): single; cdecl; external libcglm;
function glmc_ease_back_out(t: single): single; cdecl; external libcglm;
function glmc_ease_back_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_elast_in(t: single): single; cdecl; external libcglm;
function glmc_ease_elast_out(t: single): single; cdecl; external libcglm;
function glmc_ease_elast_inout(t: single): single; cdecl; external libcglm;
function glmc_ease_bounce_out(t: single): single; cdecl; external libcglm;
function glmc_ease_bounce_in(t: single): single; cdecl; external libcglm;
function glmc_ease_bounce_inout(t: single): single; cdecl; external libcglm;

// === Konventiert am: 16-2-26 19:44:57 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
