SEARCH_DIR("/lib/x86_64-linux-gnu/")
SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/11/")
SEARCH_DIR("/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/opengl/lib/x86_64-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/freetype/lib/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/packager/units/x86_64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/httpd22/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gdbint/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/sqlite/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/cdrom/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/zorba/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/chm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/symbolic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libcurl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/wasmtime/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ldap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/regexpr/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/tcl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/httpd24/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/oracle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libgd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pastojs/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libusb/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libvlc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libmagic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/openssl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/bfd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/mysql/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gtk1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/bzip2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libcups/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/modplug/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ibase/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/a52/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/openal/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opencl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fftw/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libpng/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/tplylib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/uuid/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/users/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/numlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/odbc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/lua/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/mad/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/hermes/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/jni/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/sdl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libgc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-mustache/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/zlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/dts/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libenet/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pthreads/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libffi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libxml2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/graph/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gnome1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ncurses/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/webidl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/syslog/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/imlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libsee/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengles/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libnettle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/xforms/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gnutls/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libtar/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/postgres/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/cairo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/utmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/dblib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fppkg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/dbus/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gitlab/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/newt/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/proj4/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/aspell/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pxlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fv/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/svgalib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/googleapi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/odata/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ptc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/x11/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-css/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ggi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rsvg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/unzip/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pcap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gdbm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gst/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/bin/x86_64-linux/")
INPUT(
/lib/x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/si_c.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/abitag.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Versuche/shader_test_cpp/lib/x86_64-linux/project1.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/Versuche/shader_test_cpp/lib/x86_64-linux/project1.or
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/system.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/lnfodwrf.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/exeinfo.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/strings.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/fpintres.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/objpas.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengl/gl.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengl/glu.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengl/glut.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/x86_64-linux/oglvector.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/x86_64-linux/oglmatrix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/sysutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/dynlibs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/linux.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/baseunix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/errors.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/sysconst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unixtype.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unixutil.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/dl.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/ctypes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/math.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengl/freeglut.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/classes.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/dialogs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/clipbrd.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/OpenGL_3.3/units/lib/x86_64-linux/dglOpenGL.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/types.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/typinfo.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/rtlconsts.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/sortbase.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/system.uitypes.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lmessages.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lresources.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclintf.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/interfacebase.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclstrconsts.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lcltype.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/forms.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/controls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/themes.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/graphics.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/buttons.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/buttonpanel.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/stdctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/extctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclclasses.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/menus.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/dialogres.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/graphtype.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/fileutil.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazfileutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazstringutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazloggerbase.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsreferences.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/fpcadds.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazclasses.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazutf8.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazmethodlist.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/cwstring.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/strutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/initc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unixcp.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/translations.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/jsonscanner.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/jsonparser.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/fpjson.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lconvencoding.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/avglvltree.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/stringhashlist.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/jsonreader.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/variants.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/contnrs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/varutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/masks.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazutilsstrconsts.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/dos.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/codepagescommon.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/codepagesasian.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/avl_tree.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazdbglog.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclproc.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazconfigstorage.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/dynqueue.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazutilities.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazutf16.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/laztracer.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/graphmath.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/utf8process.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazsysutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/maps.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpimage.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclplatformdef.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/intfgraphics.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/integerlist.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazversion.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpreadbmp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpwritebmp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/bmpcomn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpreadpng.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpwritepng.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpreadtiff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpwritetiff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fptiffcmn.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclversion.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/icnstypes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpimgcmn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/pngcomn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/zstream.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/zbase.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/gzio.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/hash/crc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/zdeflate.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/zinflate.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/trees.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/adler.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/infblock.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/infutil.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/infcodes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/inftrees.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/inffast.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpcolorspace.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpcanvas.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpreadpnm.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpwritepnm.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpreadjpeg.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpwritejpeg.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpreadgif.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/lclrescache.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/clipping.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/jpegcomn.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jpeglib.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdapimin.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdatasrc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdapistd.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jmorecfg.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdeferr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jinclude.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jerror.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jmemmgr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdmarker.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdinput.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcomapi.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jmemnobs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdmaster.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdcolor.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdsample.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdpostct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jddctmgr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdphuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdhuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdcoefct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdmainct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jquant1.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jquant2.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdmerge.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jidctfst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jidctint.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jidctflt.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jidctred.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcapistd.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcapimin.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jdatadst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcparam.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcinit.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcmarker.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcphuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jchuff.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcmaster.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jccolor.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcsample.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcprepct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcdctmgr.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jccoefct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jcmainct.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jfdctint.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jfdctfst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/jfdctflt.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/syncobjs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/system.timespan.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/tmschema.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/fgl.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-process/process.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-process/pipes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/termio.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/custapp.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/customtimer.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/actnlist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/helpintfs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/imglist.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/singleinstance.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wslclclasses.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fpimgcanv.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/fppixlcanv.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/pixtools.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/ellipses.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/polygonfilltools.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsimglist.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsproc.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsfactory.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/propertystorage.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/rttiutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsmenus.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazlogger.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/chm/fasthtmlparser.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wscontrols.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsforms.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/imagelistcache.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/textstrings.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/extendedstrings.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsstdctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsbuttons.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/popupnotifier.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsextctrls.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/wsdialogs.o
/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/taskdlgemulation.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/dateutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/x11/x.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/x11/xlib.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/x11/xutil.o
)
INPUT(
-ldl
-ldl
-lX11
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o
/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
