unit ftoption;

interface

{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}

const
  FT_RENDER_POOL_SIZE = 16384;
  FT_MAX_MODULES = 32;
  TT_CONFIG_OPTION_MAX_RUNNABLE_OPCODES = 1000000;
  T1_MAX_DICT_DEPTH = 5;
  T1_MAX_SUBRS_CALLS = 16;
  T1_MAX_CHARSTRINGS_OPERANDS = 256;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_X1 = 500;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_Y1 = 400;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_X2 = 1000;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_Y2 = 275;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_X3 = 1667;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_Y3 = 275;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_X4 = 2333;
  CFF_CONFIG_OPTION_DARKENING_PARAMETER_Y4 = 0;

implementation

end.
